version: '3.8'

services:
  kafka-producer:
    build:
      context: ./kafka-producer
    restart: on-failure
    ports:
      - "8081:8080"

  kafka-consumer:
    build:
      context: ./kafka-consumer
    restart: on-failure
    ports:
      - "8082:8080"
