server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template:
      default-topic: ${KAFKA_DEFAULT_TOPIC:rotiez-topic}
    consumer:
      group-id: kafka-consumers
